export type { GameModule, IllegalMoveCode } from "./contract.js";
export { IllegalMove, isIllegalMove } from "./contract.js";
export {
  codenames,
  initialState,
  reducer,
  viewFor,
} from "./codenames/index.js";
export type {
  Action,
  Card,
  CardKind,
  Clue,
  CodenamesConfig,
  Concept,
  GameState,
  Lang,
  Phase,
  Player,
  PlayerView,
  Role,
  Team,
  ViewCard,
} from "./codenames/index.js";
export {
  buildPartnerMissionBoard,
  initialPartnerMissionState,
  normalizePartnerName,
  partnerMission,
  partnerMissionReducer,
  partnerMissionViewFor,
  PARTNER_BOARD_SIZE,
  PARTNER_DECOY_COUNT,
  PARTNER_MAX_FIELD_NOTE_LENGTH,
  PARTNER_MAX_NAME_LENGTH,
  PARTNER_MAX_SIGNAL_COUNT,
  PARTNER_MAX_SIGNAL_LENGTH,
  PARTNER_MIN_SIGNAL_COUNT,
  PARTNER_TARGET_COUNT,
  PARTNER_TRAP_COUNT,
} from "./partnerMission/index.js";
export type {
  LockedPartnerGuesses,
  PartnerCardKind,
  PartnerFieldAgentView,
  PartnerFieldCard,
  PartnerLeadCard,
  PartnerMissionAction,
  PartnerMissionCapabilities,
  PartnerMissionCard,
  PartnerMissionConfig,
  PartnerMissionLeadView,
  PartnerMissionOnboardingView,
  PartnerMissionPhase,
  PartnerMissionPlayer,
  PartnerMissionRole,
  PartnerMissionSignal,
  PartnerMissionState,
  PartnerMissionView,
  PartnerPreviousTurn,
  PartnerReveal,
  PartnerTurnStopReason,
} from "./partnerMission/index.js";
